"""
Mail Agent state definitions for A2A protocol task handling.

This module defines the TypedDict structures for Mail Agent state management,
following the A2A protocol's task state model. The state tracks email operations
including composition, sending, and webhook processing.

Usage:
    from info_agent.agents.mail.state import MailAgentState, EmailTaskState

    # Initialize state for send-email task
    state: MailAgentState = {
        "task_id": "task-123",
        "skill_id": "send-email",
        "status": "submitted",
        "email_task": {
            "to_address": "user@example.com",
            "subject": "Meeting Request",
            "instructions": "Write a professional email...",
        }
    }
"""

from typing import Any, Literal, TypedDict


class EmailTaskState(TypedDict, total=False):
    """
    State for email-specific task data.

    This tracks the email operation details including recipient,
    subject, and composition instructions or webhook data.

    Attributes:
        to_address: Recipient email address (required for send-email).
        subject: Email subject line (optional, can be generated).
        instructions: Instructions for LLM to compose email body (for send-email).
        from_address: Sender email address (for receive-email-webhook).
        body_text: Email body text (for receive-email-webhook).
        message_id: Email message ID (for receive-email-webhook).
        thread_id: Email thread ID (optional).
        attachments: List of email attachments (optional).
    """

    # Common fields
    to_address: str
    subject: str
    thread_id: str | None

    # Send-email specific
    instructions: str

    # Receive-email-webhook specific
    from_address: str
    body_text: str
    message_id: str
    attachments: list[dict[str, Any]]

    # Composed/parsed data
    composed_body: str
    composed_subject: str
    parsed_data: dict[str, Any]


class MailAgentState(TypedDict):
    """
    Complete state for Mail Agent A2A task handling.

    This follows the A2A protocol's task state model, tracking the
    lifecycle of email operations from submission to completion.

    Attributes:
        task_id: Unique identifier for the A2A task (required).
        skill_id: ID of the skill being executed (required).
        status: Current task status (required).
        email_task: Email-specific task data (required).
        result: Task result data (optional, set on completion).
        error: Error message (optional, set on failure).
        payload: Original task payload (optional).
    """

    # Required A2A task fields
    task_id: str
    skill_id: Literal["send-email", "receive-email-webhook"]
    status: Literal["submitted", "working", "completed", "failed", "cancelled"]

    # Email task data
    email_task: EmailTaskState

    # Optional fields
    result: dict[str, Any] | None
    error: str | None
    payload: dict[str, Any] | None


class SendEmailPayload(TypedDict, total=False):
    """
    Payload structure for send-email skill.

    Attributes:
        to_address: Recipient email address (required).
        instructions: Instructions for email composition (required).
        subject: Optional subject line (can be generated by LLM).
        thread_id: Optional thread ID for email threading.
    """

    to_address: str
    instructions: str
    subject: str | None
    thread_id: str | None


class ReceiveEmailWebhookPayload(TypedDict):
    """
    Payload structure for receive-email-webhook skill.

    This matches the WebhookPayload structure from the email module.

    Attributes:
        event: Event type (e.g., "email.received") (required).
        message_id: Unique message ID (required).
        from_address: Sender email address (required).
        to_address: Recipient email address (required).
        subject: Email subject line (required).
        body: Email body text (required).
        thread_id: Optional thread ID.
        attachments: Optional list of attachments.
        received_at: ISO timestamp when email was received (required).
    """

    event: str
    message_id: str
    from_address: str
    to_address: str
    subject: str
    body: str
    thread_id: str | None
    attachments: list[dict[str, Any]]
    received_at: str


class SendEmailResult(TypedDict):
    """
    Result structure for successful send-email execution.

    Attributes:
        message_id: Unique ID of the sent message.
        to_address: Recipient email address.
        subject: Final email subject line.
        body_preview: Preview of the email body (first 200 chars).
        sent_at: ISO timestamp when email was sent.
    """

    message_id: str
    to_address: str
    subject: str
    body_preview: str
    sent_at: str


class ReceiveEmailWebhookResult(TypedDict):
    """
    Result structure for successful receive-email-webhook execution.

    Attributes:
        message_id: Unique ID of the received message.
        from_address: Sender email address.
        subject: Email subject line.
        parsed_data: Structured data extracted from email.
        processed_at: ISO timestamp when webhook was processed.
    """

    message_id: str
    from_address: str
    subject: str
    parsed_data: dict[str, Any]
    processed_at: str
